### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by sfc-gh-brsmith** [brundonsmith/crowdx#1]
Hi, I was thinking of using this code but I didn't see a license. Could you add one so it's more clear under what circumstances the code can be re-used?

**Comment by brundonsmith** [comment]
Hey! The package.json has it marked as `"MIT"` so you should be good to go

I will say- this probably isn't production-ready :) I'm pretty sure it has some memory leaks and it's never been tested in a real-world application. That said, feel free to do what you want with it!
